[package]
name = "helper_lib"
version = "0.2.0"
edition = "2024"


[features]
default = ["log"]
# default = ["log", "quitter"]
log = ["dep:log", "dep:simplelog", "dep:time"]
asyncs = ["dep:tokio"]
clipboard = ["dep:arboard"]
datetime = ["dep:chrono"]
llm = ["dep:anyhow", "dep:base64", "dep:nalgebra", "dep:reqwest", "dep:serde_json"]
quitter = ["dep:crossterm", "dep:termios"]
regex = ["dep:regex"]
sql = ["dep:anyhow", "dep:chrono", "dep:hex", "dep:rusqlite", "dep:zstd"]
all = ["log", "asyncs", "clipboard", "datetime", "llm", "quitter", "regex", "sql"]

[dependencies]
anyhow = { version = "1", optional = true }
arboard = { version = "3", optional = true }
base64 = { version = "0.22", optional = true }
chrono = { version = "0.4", optional = true }
hex = { version = "0.4", optional = true }
log = { version = "0.4", optional = true }
nalgebra = { version = "0.34", optional = true }
regex = { version = "1", optional = true }
reqwest = { version = "0.13", optional = true }
rusqlite = { version = "0.39", features = ["bundled", "chrono"], optional = true }
serde_json = { version = "1", optional = true }
simplelog = { version = "0.12", optional = true }
time = { version = "0.3", optional = true }
tokio = { version = "1", features = ["full"], optional = true }
zstd = { version = "0.13", optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
termios = { version = "0.3", optional = true }

[target.'cfg(target_os = "windows")'.dependencies]
crossterm = { version = "0.29", optional = true }
